In [7]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [8]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [9]:
healthexp = sns.load_dataset('healthexp')

healthexp.head(100)

    Year        Country  Spending_USD  Life_Expectancy
0   1970        Germany       252.311             70.6
1   1970         France       192.143             72.2
2   1970  Great Britain       123.993             71.9
3   1970          Japan       150.437             72.0
4   1970            USA       326.961             70.9
..   ...            ...           ...              ...
95  1991         Canada      1805.209             77.6
96  1991         France      1558.033             77.2
97  1991  Great Britain       842.797             75.9
98  1991          Japan      1166.430             79.1
99  1991            USA      2901.589             75.5

[100 rows x 4 columns]

In [10]:
healthexp = pd.get_dummies(healthexp)
healthexp

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,70.6,False,False,True,False,False,False
1,1970,192.143,72.2,False,True,False,False,False,False
2,1970,123.993,71.9,False,False,False,True,False,False
3,1970,150.437,72.0,False,False,False,False,True,False
4,1970,326.961,70.9,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
269,2020,6938.983,81.1,False,False,True,False,False,False
270,2020,5468.418,82.3,False,True,False,False,False,False
271,2020,5018.700,80.4,False,False,False,True,False,False
272,2020,4665.641,84.7,False,False,False,False,True,False
273,2020,11859.179,77.0,False,False,False,False,False,True

In [ ]:
X = healthexp.drop(['Life_Expectancy'], axis=1)
y = healthexp['Life_Expectancy']


X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=42)


rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)

pre = rfr.predict(X_test)
pre.shape
# MAE = Mean_Absolute_Error
# MSE = Mean_Square_Error

(55,)

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

mae = mean_absolute_error(y_test, pre)
mse = mean_squared_error(y_test, pre)

r2 = r2_score(y_test, pre)

print(mae)
print(mse)
print(r2)

0.28245454545453585
0.13684990909089864
0.9887906792837238